fix: ModuleNotFoundError: No module named 'ImageReward'
missing requirements.txt dependency

fixes the following issue:

```
[2024-06-04 22:26] Traceback (most recent call last):
  File "/workspace/comfyui_launcher_projects/comfyui-strimmlarns-aesthetic-score/comfyui/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/comfyui_launcher_projects/comfyui-strimmlarns-aesthetic-score/comfyui/custom_nodes/Endless-Nodes/__init__.py", line 7, in <module>
    from .endless_nodes import *
  File "/workspace/comfyui_launcher_projects/comfyui-strimmlarns-aesthetic-score/comfyui/custom_nodes/Endless-Nodes/endless_nodes.py", line 52, in <module>
    import ImageReward as RM
ModuleNotFoundError: No module named 'ImageReward'
```